/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tobi_mc_parser_Parser */

#ifndef _Included_com_tobi_mc_parser_Parser
#define _Included_com_tobi_mc_parser_Parser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tobi_mc_parser_Parser
 * Method:    parseProgram
 * Signature: ()Lcom/tobi/mc/parser/Node;
 */
JNIEXPORT jobject JNICALL Java_com_tobi_mc_parser_Parser_parseProgram
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
