package com.tobi.mc.parser.ast.lexer

enum class LexerNodeType(val parserId: Int, val representation: String = "", val hasValue: Boolean = false) {

    IDENTIFIER(2, "identifier", true),
    CONSTANT(3, "constant", true),
    TEXT(4, "string", true),
    LE_OP(5, "<="),
    GE_OP(6, ">="),
    EQ_OP(7, "=="),
    NE_OP(8, "!="),
    EXTERN(9, "extern"),
    AUTO(10, "auto"),
    INT(11, "int"),
    STRING(12, "string"),
    VOID(13, "void"),
    FUNCTION(14, "function"),
    IF(15, "if"),
    ELSE(16, "else"),
    WHILE(17, "while"),
    CONTINUE(18, "continue"),
    BREAK(19, "break"),
    RETURN(20, "return"),
    COMMA(21, ","),
    MINUS(22, "-"),
    ADD(23, "+"),
    MULTIPLY(24, "*"),
    DIVIDE(25, "/"),
    MOD(26, "%"),
    GREATER_THAN(27, ">"),
    LESS_THAN(28, "<"),
    SEMI_COLON(29, ";"),
    ASSIGNMENT(30, "="),
    LEFT_CURLY(31, "{"),
    RIGHT_CURLY(32, "}"),
    LEFT_BRACKET(33, "("),
    RIGHT_BRACKET(34, ")"),
    NOT(35, "!"),
    STRING_CONCAT(36, "++")
}